### ISSUE TITLE
The mod is incompatible with 1.19.4

### ISSUE THREAD

**Issue by Finoway** [Withicality/GamemodeDetector#1]
Hello,

The mod does not work by default in 1.19.4 because you put in dependence the version 1.19.3 of minecraft, to be able to use it already compiled it is just enough to change in the file "fabric.mod.json" the version of minecraft and it seems to work without problem.

**Comment by widz-a** [comment]
Hello!

This mod was originally designed for 1.19.3. I'm currently busy irl so I haven't updated it. While it's possible to change the setting in "fabric.mod.json", I'm planning on updating the mod to 1.19.4 and adding a section to disable the mod in-game as joining a big server with this mod may spam your chat. 

Thank you for using my mod <3

**Comment by widz-a** [comment]
Hello again!

The mod has been properly updated to 1.1 alongside with other features. You can download it by clicking [here](https://modrinth.com/mod/gamemode-detector/version/1.1) or [here](https://github.com/Withicality/GamemodeDetector/releases/tag/v1.1).

Again, thank you for using my mod <3
