### ISSUE TITLE
Chat flood

### ISSUE THREAD

**Issue by SkyWors** [Withicality/GamemodeDetector#2]
Hey! Great mod!
The chat is quickly filling on some servers.
An option to choose between chat and actionbar would be a good idea.

**Comment by widz-a** [comment]
Hello!
Starting from v1.1, you can disable the mod if you have ModMenu installed. This will disable the logger. 
Not noticed that this mod isnt meant for big server but rather, small SMP server with friends.
Thanks!

**Comment by widz-a** [comment]
Update: I've added the option to choose between chat and actionbar. You can toggle between these using ModMenu.
